version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.26
    restart: always
    ports:
      - "3037:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airservice_db
      MYSQL_USER: geouser
      MYSQL_PASSWORD: 1234

  backend:
    container_name: airservice_test_task
    #image: scanda/airservice
    restart: always

    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
    environment:
      SERVER_PORT: 8080

